package demo.repository;

import demo.model.ModelData;
import demo.model.ModelDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepositoryData {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	long countByExample(ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int deleteByExample(ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int insert(ModelData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int insertSelective(ModelData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	List<ModelData> selectByExample(ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	ModelData selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int updateByExampleSelective(@Param("record") ModelData record, @Param("example") ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int updateByExample(@Param("record") ModelData record, @Param("example") ModelDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int updateByPrimaryKeySelective(ModelData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table select_plus_db
	 * @mbg.generated  Tue May 12 17:26:00 JST 2020
	 */
	int updateByPrimaryKey(ModelData record);
}